const BASE_URL = "http://testapi.eazytechmm.com/";
const API_URL = BASE_URL + "api/";
const LOGIN_URL = API_URL + "login";
const REGISTER_URL = API_URL + "register";
const POST_URL = API_URL + "public/post";
const CREATE_URL = API_URL + "post/create";
const CAT_URL = API_URL + "category/all";
const CAT_BY_URL = API_URL + "public/post/category?category_id=";
const PROFILE_URL = API_URL + "login/user";
const USER_POST_URL = API_URL + "user/post";
const IMG_BASE_URL = BASE_URL + "public";
